version: '3.6'

services:
  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    volumes: 
      - ./frontend:/usr/share/nginx/html
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend/
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - db

  db:
    build: ./db/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: appdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
